language: php
php:
  - 7.2

install:
  - composer install --prefer-dist

script:
  - composer cs
  - composer static-analysis
  - composer test

cache:
  directories:
    - $HOME/.composer/cache/files
